package io.github.springapidiff.diff;

public enum ChangeType {
    ENDPOINT_REMOVED,
    ENDPOINT_ADDED,
    PATH_VARIABLE_REMOVED,
    PATH_VARIABLE_TYPE_CHANGED,
    REQUIRED_QUERY_PARAM_ADDED,
    QUERY_PARAM_BECAME_REQUIRED,
    QUERY_PARAM_REMOVED,
    QUERY_PARAM_TYPE_CHANGED,
    REQUEST_BODY_FIELD_REMOVED,
    REQUIRED_REQUEST_BODY_FIELD_ADDED,
    REQUEST_BODY_FIELD_BECAME_REQUIRED,
    REQUEST_BODY_FIELD_TYPE_CHANGED,
    RESPONSE_FIELD_REMOVED,
    RESPONSE_FIELD_TYPE_CHANGED,
    RESPONSE_FIELD_ADDED
}
